name: Make Graph

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        path: ow-timeline
    - name: Checkout mod database
      uses: actions/checkout@v3
      with:
        repository: Raicuparta/ow-mod-db
        ref: master
        fetch-depth: 0
        path: ow-mod-db
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install matplotlib
    - name: Run script
      run: |
        python ow-timeline/main.py ow-mod-db/database.json all
    - name: Upload Timeline Artifact
      uses: actions/upload-artifact@v3
      with:
        name: OW Mods Timeline (all)
        path: "OW Mods Timeline (all).png"
